# Generated by Django 3.1.4 on 2020-12-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20201214_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='slug',
            new_name='url',
        ),
    ]
