# Generated by Django 3.1.4 on 2020-12-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20201214_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='url',
            new_name='slug',
        ),
    ]
